branches:
  only:
  - master
services: 
- docker
push: &push
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - docker version
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker images
        - |
          for i in `docker images --format {{.Repository}}:{{.Tag}}`; do
            if [[ $TRAVIS_EVENT_TYPE == "push" ]]; then 
              docker push $i;
            fi
          done
alpine: &alpine
      stage: Build
      os: linux
      language: shell
      script:
        - docker-compose -f dist/alpine/docker-compose.yml build
        - docker rmi alpine:3.11
        - docker system prune -f
      <<: *push
debian: &debian
      stage: Build
      os: linux
      language: shell
      script:
        - docker-compose -f dist/debian/docker-compose.yml build
        - docker rmi debian:9.12-slim
        - docker system prune -f
      <<: *push
jobs:
  include:
    - <<: *alpine
      env:
      - LABEL: Alpine
      - PY_VERSION: 3.8
      - CONDA_VERSION: 4.8.2
      - PY_LABEL: py38_
      - CONDA_MD5: cbda751e713b5a95f187ae70b509403f
    - <<: *alpine
      env:
      - LABEL: Alpine
      - PY_VERSION: 3.7
      - CONDA_VERSION: 4.8.2
      - PY_LABEL: py37_
      - CONDA_MD5: 87e77f097f6ebb5127c77662dfc3165e
    - <<: *alpine
      env:
      - LABEL: Alpine
      - PY_VERSION: 3.6
      - CONDA_VERSION: 4.4.10
      - CONDA_MD5: bec6203dbb2f53011e974e9bf4d46e93
    - <<: *debian
      env:
      - LABEL: Debian
      - PY_VERSION: 3.8
      - CONDA_VERSION: 4.8.2
      - PY_LABEL: py38_
      - CONDA_MD5: cbda751e713b5a95f187ae70b509403f
    - <<: *debian
      env:
      - LABEL: Debian
      - PY_VERSION: 3.7
      - CONDA_VERSION: 4.8.2
      - PY_LABEL: py37_
      - CONDA_MD5: 87e77f097f6ebb5127c77662dfc3165e
    - <<: *debian
      env:
      - LABEL: Debian
      - PY_VERSION: 3.6
      - CONDA_VERSION: 4.4.10
      - CONDA_MD5: bec6203dbb2f53011e974e9bf4d46e93
