branches:
	only:
	- master
services: 
- docker
push: &push
			before_install:
				- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
				- |
					sudo add-apt-repository $(echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tr -d '\t')
				- sudo apt-get update
				- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
				- docker version
			after_success:
				- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
				- docker images
				- |
					for i in `docker images --format {{.Repository}}:{{.Tag}}`; do
						if [[ $TRAVIS_EVENT_TYPE == "push" ]]; then 
							docker push $i;
						fi
					done
alpine: &alpine
			stage: Build
			os: linux
			language: shell
			script:
				- IMAGE=$(docker-compose -f $COMPOSE_FILE images app | tail -1 | awk '{print $2}')
				- TAG=$(docker-compose -f $COMPOSE_FILE images app | tail -1 | awk '{print $3}')
				- docker-compose -f $COMPOSE_FILE build
				- docker tag ${IMAGE}:${TAG} ${IMAGE}:${TAG}-${TRAVIS_COMMIT:0:7}
				- docker rmi alpine:3.11
				- docker system prune -f
			<<: *push
debian: &debian
			stage: Build
			os: linux
			language: shell
			script:
				- IMAGE=$(docker-compose -f $COMPOSE_FILE images app | tail -1 | awk '{print $2}')
				- TAG=$(docker-compose -f $COMPOSE_FILE images app | tail -1 | awk '{print $3}')
				- docker-compose -f $COMPOSE_FILE build
				- docker tag ${IMAGE}:${TAG} ${IMAGE}:${TAG}-${TRAVIS_COMMIT:0:7}
				- |
					[ "$PY_VER" == "3.8" ] && docker tag ${IMAGE}:${TAG} ${IMAGE}:latest
				- docker rmi debian:9.12-slim
				- docker system prune -f
			<<: *push
jobs:
	include:
		- <<: *alpine
			env:
			- LABEL: alpine
			- PY_VERSION: 3.8
			- CONDA_VERSION: 4.8.2
			- PY_LABEL: py38_
			- CONDA_MD5: cbda751e713b5a95f187ae70b509403f
			- COMPOSE_FILE: dist/alpine/docker-compose.yml
		- <<: *alpine
			env:
			- LABEL: alpine
			- PY_VERSION: 3.7
			- CONDA_VERSION: 4.8.2
			- PY_LABEL: py37_
			- CONDA_MD5: 87e77f097f6ebb5127c77662dfc3165e
			- COMPOSE_FILE: dist/alpine/docker-compose.yml
		- <<: *alpine
			env:
			- LABEL: alpine
			- PY_VERSION: 3.6
			- CONDA_VERSION: 4.4.10
			- CONDA_MD5: bec6203dbb2f53011e974e9bf4d46e93
			- COMPOSE_FILE: dist/alpine/docker-compose.yml
		- <<: *debian
			env:
			- LABEL: debian
			- PY_VERSION: 3.8
			- CONDA_VERSION: 4.8.2
			- PY_LABEL: py38_
			- CONDA_MD5: cbda751e713b5a95f187ae70b509403f
			- COMPOSE_FILE: dist/debian/docker-compose.yml
		- <<: *debian
			env:
			- LABEL: debian
			- PY_VERSION: 3.7
			- CONDA_VERSION: 4.8.2
			- PY_LABEL: py37_
			- CONDA_MD5: 87e77f097f6ebb5127c77662dfc3165e
			- COMPOSE_FILE: dist/debian/docker-compose.yml
		- <<: *debian
			env:
			- LABEL: debian
			- PY_VERSION: 3.6
			- CONDA_VERSION: 4.4.10
			- CONDA_MD5: bec6203dbb2f53011e974e9bf4d46e93
			- COMPOSE_FILE: dist/debian/docker-compose.yml
