branches:
  only:
  - master
services: 
- docker
push: &push
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker images
        - |
          for i in `docker images --format {{.Repository}}:{{.Tag}}`; do
            if [[ $TRAVIS_EVENT_TYPE == "push" ]]; then 
              docker push $i;
            fi
          done
alpine: &alpine
      stage: Build
      os: linux
      language: shell
      script:
        - docker-compose -f dist/alpine/docker-compose.yml build
        - docker rmi alpine:3.11
      <<: *push
debian: &debian
      stage: Build
      os: linux
      language: shell
      script:
        - docker-compose -f dist/debian/docker-compose.yml build
        - docker rmi debian:9.12-slim
      <<: *push
jobs:
  include:
    - <<: *alpine
      env:
      - CONDA_VERSION: 4.8.2
      - PY_VERSION: 3.8
      - PY_LABEL: py38_
      - CONDA_MD5: cbda751e713b5a95f187ae70b509403f
    - <<: *alpine
      env:
      - CONDA_VERSION: 4.8.2
      - PY_VERSION: 3.7
      - PY_LABEL: py37_
      - CONDA_MD5: 87e77f097f6ebb5127c77662dfc3165e
    - <<: *alpine
      env:
      - CONDA_VERSION: 4.4.10
      - PY_VERSION: 3.6
      - CONDA_MD5: bec6203dbb2f53011e974e9bf4d46e93
    - <<: *debian
      env:
      - CONDA_VERSION: 4.8.2
      - PY_VERSION: 3.8
      - PY_LABEL: py38_
      - CONDA_MD5: cbda751e713b5a95f187ae70b509403f
    - <<: *debian
      env:
      - CONDA_VERSION: 4.8.2
      - PY_VERSION: 3.7
      - PY_LABEL: py37_
      - CONDA_MD5: 87e77f097f6ebb5127c77662dfc3165e
    - <<: *debian
      env:
      - CONDA_VERSION: 4.4.10
      - PY_VERSION: 3.6
      - CONDA_MD5: bec6203dbb2f53011e974e9bf4d46e93
