name: Development
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.9
            py_label: py39_
            conda_md5: 8c69f65a4ae27fb41df0fe552b4a8a3b
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.8
            py_label: py38_
            conda_md5: 14da4a9a44b337f7ccb8363537f65b9c
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.7
            py_label: py37_
            conda_md5: 9f186c1d86c266acc47dbc1603f0e2ed
          - distro: alpine
            conda_ver: 4.5.4
            py_ver: 3.6
            conda_md5: a946ea1d0c4a642ddf0c3a26a18bb16d
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.9
            py_label: py39_
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.8
            py_label: py38_
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.7
            py_label: py37_
          - distro: debian
            conda_ver: 4.5.4
            py_ver: 3.6
    env:
      DISTRO: ${{matrix.distro}}
      CONDA_VER: ${{matrix.conda_ver}}
      PY_VER: ${{matrix.py_ver}}
      PY_LABEL: ${{matrix.py_label}}
      CONDA_MD5: ${{matrix.conda_md5}}
      DOCKER_CLIENT_TIMEOUT: "120"
      COMPOSE_HTTP_TIMEOUT: "120"
    steps:
      - uses: actions/checkout@v2
      - name: Compile image
        run: |
          docker-compose -f dist/${DISTRO}/docker-compose.yaml build
          IMAGE=$(docker images --filter "reference=datajoint/*" --format "{{.Repository}}")
          TAG=$(docker images --filter "reference=datajoint/*" --format "{{.Tag}}")
          docker save "${IMAGE}:${TAG}" | gzip > "${CONDA_VER}-py${PY_VER}-${DISTRO}.tar.gz"
      - name: Add image artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{format('{0}-py{1}-{2}', matrix.conda_ver, matrix.py_ver, matrix.distro)}}
          path: >
            ${{format('{0}-py{1}-{2}.tar.gz', matrix.conda_ver, matrix.py_ver, matrix.distro)}}
          retention-days: 1
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.9
            package_manager: apk
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.8
            package_manager: apk
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.7
            package_manager: apk
          - distro: alpine
            conda_ver: 4.5.4
            py_ver: 3.6
            package_manager: apk
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.9
            package_manager: apt
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.8
            package_manager: apt
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.7
            package_manager: apt
          - distro: debian
            conda_ver: 4.5.4
            py_ver: 3.6
            package_manager: apt
    env:
      DISTRO: ${{matrix.distro}}
      CONDA_VER: ${{matrix.conda_ver}}
      PY_VER: ${{matrix.py_ver}}
      PACKAGE_MANAGER: ${{matrix.package_manager}}
    steps:
      - uses: actions/checkout@v2
      - name: Fetch image artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{format('{0}-py{1}-{2}', matrix.conda_ver, matrix.py_ver, matrix.distro)}}
      - name: Run integration tests
        run: |
          export HOST_UID=$(id -u)
          docker load < "${CONDA_VER}-py${PY_VER}-${DISTRO}.tar.gz"
          tests/main.sh
  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.9
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.8
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.7
          - distro: alpine
            conda_ver: 4.5.4
            py_ver: 3.6
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.9
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.8
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.7
          - distro: debian
            conda_ver: 4.5.4
            py_ver: 3.6
    env:
      DISTRO: ${{matrix.distro}}
      CONDA_VER: ${{matrix.conda_ver}}
      PY_VER: ${{matrix.py_ver}}
      DOCKER_USERNAME: ${{secrets.docker_username}}
      DOCKER_PASSWORD: ${{secrets.docker_password}}
    steps:
      - name: Fetch image artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{format('{0}-py{1}-{2}', matrix.conda_ver, matrix.py_ver, matrix.distro)}}
      - name: Publish image
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker load < "${CONDA_VER}-py${PY_VER}-${DISTRO}.tar.gz"
          IMAGE=$(docker images --filter "reference=datajoint/*" --format "{{.Repository}}")
          TAG=$(docker images --filter "reference=datajoint/*" --format "{{.Tag}}")
          docker push "${IMAGE}:${TAG}"
          docker tag "${IMAGE}:${TAG}" "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
          docker push "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
          [ "$PY_VER" == "3.9" ] && [ "$DISTRO" == "debian" ] \
                  && docker tag "${IMAGE}:${TAG}" "${IMAGE}:latest" \
                  && docker push "${IMAGE}:latest" \
              || echo "skipping 'latest' tag..."
  publish-docs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      # - name: Upload docs artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: docs-html
      #     path: docs/_build/html/
      #     retention-days: 1
      - name: Commit documentation changes
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git \
              --branch gh-pages --single-branch gh-pages
          rm -R gh-pages/*
          cp -r docs/_build/html/* gh-pages/
          cp .gitignore gh-pages/
          touch gh-pages/.nojekyll
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add . --all
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{secrets.GITHUB_TOKEN}}